#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_GO_MODULE_REMOTE_IMPORT_PATHS_GIT_SERVER text "Git Server Host (example: http://10.0.0.1:8888)"
}

check $@
