#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_GOMIRROR_HACK_GITLAB_SOURCE_HOST text "Source Host (example: 10.0.0.1:8080)"
  service::config_set SERVICE_GOMIRROR_HACK_GITLAB_TARGET_HOST text "Target Host (example: gitlab.example.com)"
}

check $@
