services:
  go-module-remote-import-paths:
    restart: always
    image: whatwewant/go-module-remote-import-paths:${SERVICE_GO_MODULE_REMOTE_IMPORT_PATHS_IMAGE_VERSION}
    platform: linux/amd64
    # ports:
    #   - 0.0.0.0:${SERVICE_GO_MODULE_REMOTE_IMPORT_PATHS_PORT}:8080
    environment:
      GIT_SERVER: ${SERVICE_GO_MODULE_REMOTE_IMPORT_PATHS_GIT_SERVER}
      
networks:
  default:
    external: true
    name: compose-ingress
