services:
  gomirror-hack-gitlab:
    restart: always
    image: whatwewant/gomirror-hack-gitlab:${SERVICE_GOMIRROR_HACK_GITLAB_IMAGE_VERSION}
    platform: linux/amd64
    # ports:
    #   - 0.0.0.0:${SERVICE_GOMIRROR_HACK_GITLAB_PORT}:8080
    environment:
      SOURCE: http://${SERVICE_GOMIRROR_HACK_GITLAB_SOURCE_HOST}
      TARGET: http://${SERVICE_GOMIRROR_HACK_GITLAB_TARGET_HOST}
      
networks:
  default:
    external: true
    name: compose-ingress
